"""add_tickers_and_ohlcv

Revision ID: abae3ec9059f
Revises: 86e144966f6f
Create Date: 2026-08-18 07:35:16.213235

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abae3ec9059f"
down_revision: Union[str, Sequence[str], None] = "86e144966f6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tickers_symbol"), "tickers", ["symbol"], unique=True)
    op.create_table(
        "ohlcv",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ticker_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("high >= low", name="ck_ohlcv_high_gte_low"),
        sa.CheckConstraint("volume >= 0", name="ck_ohlcv_volume_gte_zero"),
        sa.ForeignKeyConstraint(["ticker_id"], ["tickers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker_id", "date", name="uq_ohlcv_ticker_date"),
    )
    op.create_index(op.f("ix_ohlcv_date"), "ohlcv", ["date"], unique=False)
    op.create_index(op.f("ix_ohlcv_ticker_id"), "ohlcv", ["ticker_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ohlcv_ticker_id"), table_name="ohlcv")
    op.drop_index(op.f("ix_ohlcv_date"), table_name="ohlcv")
    op.drop_table("ohlcv")
    op.drop_index(op.f("ix_tickers_symbol"), table_name="tickers")
    op.drop_table("tickers")
    # ### end Alembic commands ###
