"""Add canonical_format_hit

Revision ID: c961f1f9fde9
Revises: 0f4a61c5ea63
Create Date: 2026-08-18 18:38:47.420221

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c961f1f9fde9"
down_revision: Union[str, Sequence[str], None] = "0f4a61c5ea63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_chunks_embedding"),
        table_name="document_chunks",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.add_column("eval_runs", sa.Column("canonical_format_hit", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("eval_runs", "canonical_format_hit")
    op.create_index(
        op.f("ix_document_chunks_embedding"),
        "document_chunks",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    # ### end Alembic commands ###
